import lib.opentopodata  as opentopodata
import lib.Tiler as Tiler

import polyline

#opentopodata.SELECT_METHOD = 'OLD'
r = opentopodata.getElevation('e{pbFdxahVBJPl@^r@FJKDSBUGeAo@QIUKSAQ@SNSXQ`@Id@Al@HhAEbAANEVM`@Yn@]h@k@x@Yh@m@hAUZWRYNa@LqAXg@Fg@Nm@ZOH_A^e@\WXqAhBg@l@[VWN@V?FG@C@@@B@F?FAF@H?L?DBHRBBBCBKDW@IAK@GDCL?DC?E?I?G@A@@@D@BDJ?D@NDJBLCL?JEFAJCXANEHAHBJLP@L@NANILIPARGHEJGHGPBJ@J@HAFEBKIQSCOGEKCIEIGGGKEI@EBGFCF@LBJBR?N?JADE@GBEBGFIRC@CACEKII?MDC?GCGAI?E?CECMGSKSIME@MFSLKHEJCJAD?NARANE^AP?PBP@J?JAHC?CAGESIQEUAMAK?GDCFIDSHGFCFCL@H?P@LALEPGHKBK@KBGDAJCDE?ECCEG?QDS@WBS@M?M@O@MFQDMDQDpAdAf@`AjAf@f@Td@b@HXJTf@PJHFLRSDEPSTMd@Mb@U`@OTAl@T`@BTCTMPUPUd@We@VQTQTULUBa@Cm@UU@a@Nc@Te@LULQREDSRGMKIg@QKUIYe@c@g@UkAg@g@aAqAeAPELEPELGNALAL?RAVCRAPEF?BDDBD?BE@KFEJCJAJCFIDQ@MAM?QAIBMBGFGRIHEBGFEJ?L@T@PDRHFDB@B?@I?KAKCQ?Q@QD_@@O@S?O@EBKDKJIRMLGDAHLJRFRBLBDD?H?F@FBB?LEH?JHBDB@BAHSFGDCFCDA@E?K?OCSCKAMBGFGDCHAJDFFHFHDJBFDBNPRJHDC@GAIAKCKFQFIDKFI@SHQHM@OAOAMMQCK@IDI@OBY@KDG?KBMCMEKAO?EEKACAEAAA@?F?H?DEBM?EBAF@JAHEVCJCBCCISECM?I?GAG@G?CAAABAFA?GAW{@RaCh@yCt@iAf@[Pc@JaEj@gB\{@Pu@N_@Ee@M_Ae@mBWaAFWL[j@[fAa@dCa@lASj@g@xA_@LSBUCQIMOY_@Qo@Ca@Ba@f@{CB_AM{ACc@YeDEc@CWCMCQCOKWKQKIKEQCUBQF]HQHSDM@QA]A]S_@a@wAyAcB}Aq@c@FMHUHOUOYWa@c@S]MQQMSQSMQMEKAUDYCSEYHw@Cc@Qi@Es@Ka@MSQKMm@Qa@_@CMSAIRILSJMBOVQ?@d@@TD@RCJ?BB?HGJA`@k@V[`@Cd@LPPTLJARIh@IR?ZPh@RlAfAVZFJJFZBj@@TARE\Id@KFO@ICc@BOHML@PJN?HGFKHYJQf@OfA?l@DTIXIVSVORCDMBK@_@AUCUBc@?a@Co@CSAUBIFKBEHCJ?J@PBLAJCHCNEHEHGBGHEJ@JFHJFDBFBF?LAJKRSPMJQFWFEBCD@HDHBJLPVRPTJL@R?PBNJJRHNHLNBR?TANANCHGN?L@HBFHFLFPHRTJJNH|@l@NXDHBJ@@?EAKAU@OCOQ[KIKKOKBGFFLBP?XFPVJRFXLl@Hl@?p@Qb@AFDHHDJBJBNDFDL@JGJENCP@HBHDBJ@TATCZBLHNFFF?FC@@ADGNCHA@AFBFHP@N?REFGAGOCOC@@R@NBPDNHFJ@PITWLSDO@SBWBKDMBOB??JAFAN?LBN@R?T?LI\CVARALCXEVIJMDWH[BOBE@G?IBI?OGEIA?DPBHFFRL^Hf@LNBDFDBDEBG@IBEFCDEFADABABCBABABABABABA@ADCF?@C?A?EAEAEEGCCACCGAEEEAC?E@C@I@C?E@C?ABAB?@@@BBD@BDDB@B@BCBCBEBSFOFGBC@E?CAQCIAE?C@AB?@A?CAEAEAE?A?A?CJAF?D@BP?N?FBBHJ@HALATAL?P@`@Dd@DRBTHFHAHABI?K?OFEDI@CH@B?BCDBP?^RJPDPDLBFFDJBJEJOf@k@BE?CAECA?AA?SMIKEGAG@G@EAKASEUC[?UC[?M@GBKD@CTH\DVBTBL@D@?@GCMAO@K?OAO?IBMFGFGFGRWLMJIHQHKJEDADG?GAEEG?CBAHBF?HKDG@GBAB?FHB?FCJOBEDEJCD@DAJEJ?JBD@FFJ@J?D?DADE@ADB@BB@LCF@DFHDTAP?FBFBBDDJBFDPDHFJFHDL@H@H?H?DDDLDH@FABC@CAIAI@E?KBIJ[?Q?UAS?IAGEECCCCCC?CDCDCDEBGBIAIAE@G@CDAFEB?DB@@FR?JDTHb@J~@Lj@?h@@PD@BQ@IBGPERAPAFGDGHW@G@KBKBIXk@T[LMJKn@Un@EHAHCDG@I?OAQGUISGS?GBGZDJBPBHe@Pa@RYROPAR@TJPHdAn@TFRCJEGK_@s@Qm@CK')
print(r)

print(polyline.decode(r['points']))

Tiler.generateMbTiles(
    minlat=37,
    maxlat=38,
    minlon=-122,
    maxlon=-121,
    srcfile='/home/ubuntu/maptiler/data/planet.mbtiles',
    outfile='/home/ubuntu/tmp.mbtiles'
)